version: '3'

services:
  parts:
    build:
      context: ./parts
    # ports:
      #- 3000:3000
  tools:
    build:
      context: ./tools
    # ports:
      #- 3001:3000
  reverse-proxy:
    build:
      context: ./nginx
    ports:
      - 8080:5000

